books/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from books import views
from books.views import SpecificIndexView

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^select/$', views.SelectorView.as_view(), name='select'),
    url(r'^(?P<languages>[\w\-\*]+)/(?P<techs>[\w\-\*]+)/(?P<tags>[\w\-\*]+)/$', SpecificIndexView.as_view(), name='specific_index'),
    url(r'^rest/status/update/$', views.StatusUpdateView.as_view(), name='status_update')
]

lessons/urls.py
from django.conf.urls import url

from lessons import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail')
]

sturm/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls.static import static
from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [

    url(r'^admin/', include(wagtailadmin_urls)),

    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^books/', decorator_include(login_required, 'books.urls', namespace="books")),
    url(r'^techs/', decorator_include(login_required, 'techs.urls', namespace="techs")),
    url(r'^projects/', decorator_include(login_required, 'projects.urls', namespace="projects")),
    url(r'^lessons/', decorator_include(login_required, 'lessons.urls', namespace="lessons")),
    url(r'^students/', decorator_include(login_required, 'students.urls', namespace="students")),

    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', login_required(search_views.search), name='search'),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:

    url(r'^', login_required(TemplateView.as_view(template_name='index.html')), name="home"),

    url(r'', decorator_include(login_required, wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lessons/models.py
from django.db import models
from modelcluster.fields import ParentalKey
from wagtail.wagtailadmin.edit_handlers import FieldPanel, PageChooserPanel, InlinePanel, StreamFieldPanel
from wagtail.wagtailcore.fields import RichTextField, StreamField
from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailembeds.blocks import EmbedBlock
from wagtail.wagtailimages.blocks import ImageChooserBlock
from wagtail.wagtailsearch import index
from wagtail.wagtailcore import blocks

import lessons
from books.models import Book
from lessons.blocks import CodeBlock


class Lesson(Page):
    parent_page_types = ['lessons.LessonIndex']

    date = models.DateField("Post date")
    body = StreamField([
        ('heading', blocks.CharBlock(classname="full title", template='blocks/heading.html')),
        ('paragraph', blocks.RichTextBlock()),
        ('code', CodeBlock()),
        ('image', ImageChooserBlock()),
        ('video', EmbedBlock()),
    ])

    search_fields = Page.search_fields + [
        index.SearchField('body'),
        index.FilterField('date'),
    ]

    content_panels = Page.content_panels + [
        FieldPanel('date'),
        StreamFieldPanel('body'),
        InlinePanel('techs', label="Mentioned technologies"),
        InlinePanel('books', label="Mentioned books"),
        InlinePanel('related_article_links', label="Related links"),
    ]


class LessonRelatedArticleLink(Orderable):
    page = ParentalKey(Lesson, related_name='related_article_links')
    name = models.CharField(max_length=255)
    url = models.URLField()

    panels = [
        FieldPanel('name'),
        FieldPanel('url'),
    ]


class LessonTechRelationship(models.Model):
    lesson = ParentalKey(Lesson, related_name='techs')
    tech = models.ForeignKey('techs.Tech')

    panels = [
        PageChooserPanel('tech', 'techs.Tech'),
    ]


class LessonBookRelationship(models.Model):
    lesson = ParentalKey(Lesson, related_name='books')
    book = models.ForeignKey(Book)

    panels = [
        PageChooserPanel('book', 'books.Book'),
    ]


class LessonIndex(Page):
    subpage_types = ['lessons.Lesson']

lessons/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views import generic

from lessons.models import Lesson


class IndexView(generic.ListView):
    template_name = 'lessons/index.html'
    context_object_name = 'lesson_list'

    def get_queryset(self):
        """Return the last five published books."""
        return Lesson.objects.all()


class DetailView(generic.DetailView):
    model = Lesson
    template_name = 'lessons/detail.html'

sturm/templates/lessons/detail.html
{% extends 'mybase.html' %}
{% load wagtailcore_tags %}

{% block content %}
    <div class="row">
        <div class="col s12 m10 push-m1 l8 push-l2">

            <div class="row">
                <h2 class="fat-header center-on-small-only">{{ lesson.title }}</h2>
            </div>

            <div class="row">
                {% include_block lesson.body %}
            </div>

        </div>
    </div>
{% endblock content %}

sturm/templates/lessons/index.html
{% extends 'mybase.html' %}
{% block content %}
    <div class="row">
        <div class="col s12 l8 push-l2">
            <div class="item-index">
                {% if lesson_list %}
                    <ul>
                        {% for lesson in lesson_list %}
                            <li class="item-card">
                                <div class="card-content">
                                    <p class="item-title">{{ lesson.title }}</p>
                                </div>
                                <div class="card-action action-buttons">
                                    <a href="{% url 'lessons:detail' lesson.id %}" class="waves-effect waves-light btn">
                                        Читать
                                    </a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>Уроков нет</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}