books/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from books import views
from books.views import SpecificIndexView

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^select/$', views.SelectorView.as_view(), name='select'),
    url(r'^(?P<languages>[\w\-\*]+)/(?P<techs>[\w\-\*]+)/(?P<tags>[\w\-\*]+)/$', SpecificIndexView.as_view(), name='specific_index'),
    url(r'^rest/status/update/$', views.StatusUpdateView.as_view(), name='status_update')
]

sturm/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls.static import static
from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [

    url(r'^admin/', include(wagtailadmin_urls)),

    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^books/', decorator_include(login_required, 'books.urls', namespace="books")),
    url(r'^techs/', decorator_include(login_required, 'techs.urls', namespace="techs")),
    url(r'^projects/', decorator_include(login_required, 'projects.urls', namespace="projects")),
    url(r'^lessons/', decorator_include(login_required, 'lessons.urls', namespace="lessons")),
    url(r'^students/', decorator_include(login_required, 'students.urls', namespace="students")),

    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', login_required(search_views.search), name='search'),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:

    url(r'^', login_required(TemplateView.as_view(template_name='index.html')), name="home"),

    url(r'', decorator_include(login_required, wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techs/urls.py
from django.conf.urls import url

from techs import views
from techs.views import CategoryIndexView

urlpatterns = [
    url(r'^main/$', views.MainView.as_view(), name='main'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<category>[\w]+)/$', CategoryIndexView.as_view(), name='category-index'),
]

techs/models.py
from django.db import models
from modelcluster.fields import ParentalKey
from taggit.managers import TaggableManager
from wagtail.wagtailadmin.edit_handlers import FieldPanel, InlinePanel, StreamFieldPanel
from wagtail.wagtailcore.fields import RichTextField, StreamField
from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailembeds.blocks import EmbedBlock
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel
from wagtail.wagtailsearch import index
from wagtail.wagtailsnippets.edit_handlers import SnippetChooserPanel

from books.ru_taggit import RuTaggedItem


class Tech(Page):
    parent_page_types = ['techs.TechIndex']

    # connections
    projects = models.ManyToManyField('projects.Project', through='projects.ProjectTechRelationship')
    lessons = models.ManyToManyField('lessons.Lesson', through='lessons.LessonTechRelationship')
    books = models.ManyToManyField('books.Book', through='books.BookTechRelationship')

    # tags
    tags = TaggableManager(through=RuTaggedItem, blank=True)

    # content

    # off_page = models.URLField(blank=True)
    # off_docs = models.URLField(blank=True)

    # descriptions = RichTextField(blank=True)
    body = RichTextField(blank=True)
    logo_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    search_fields = Page.search_fields + [
        # index.SearchField('description'),
    ]

    content_panels = Page.content_panels + [
        # FieldPanel('off_page'),
        # FieldPanel('off_docs'),
        # FieldPanel('description', classname="full"),
        FieldPanel('tags'),
        ImageChooserPanel('logo_image'),
        InlinePanel('related_article_links', label="Related article links"),
        InlinePanel('related_video_links', label="Related video links"),
    ]

    def __str__(self):
        return self.title


class TechRelatedArticleLink(Orderable):
    page = ParentalKey(Tech, related_name='related_article_links')
    name = models.CharField(max_length=255)
    description = RichTextField(blank=True)
    url = models.URLField()

    panels = [
        FieldPanel('name'),
        FieldPanel('description', classname="full"),
        FieldPanel('url'),
    ]


class TechRelatedVideoLink(Orderable):
    page = ParentalKey(Tech, related_name='related_video_links')
    name = models.CharField(max_length=255)
    description = RichTextField(blank=True)
    video = StreamField([
        ('video', EmbedBlock()),
    ], blank=True)

    panels = [
        FieldPanel('name'),
        FieldPanel('description', classname="full"),
        StreamFieldPanel('video'),
    ]


class TechStudentRelationship(models.Model):
    tech = ParentalKey(Tech, related_name='students')
    student = models.ForeignKey('students.Student')

    panels = [
        SnippetChooserPanel('student'),
    ]


class TechIndex(Page):
    subpage_types = ['techs.Tech']

techs/views.py
from operator import and_

from django.db.models import Q
from django.views import generic

from techs.models import Tech


class MainView(generic.ListView):
    template_name = 'techs/main.html'
    context_object_name = 'tech_list'

    def get_queryset(self):
        """Return the last five published books."""
        return Tech.objects.all()


class IndexView(generic.ListView):
    template_name = 'techs/index.html'
    context_object_name = 'tech_list'

    def get_criteria_list(self):
        return [~Q(pk=None)]

    def get_queryset(self):
        tech_list = Tech.objects \
            .filter(reduce(and_, self.get_criteria_list())) \
            .distinct()
        return tech_list


class CategoryIndexView(IndexView):
    def get_criteria_list(self):
        category = self.kwargs['category']

        category_criteria = Q(tags__slug=category)

        return [category_criteria]


class DetailView(generic.DetailView):
    model = Tech
    template_name = 'techs/detail.html'

# Create your views here.

sturm/templates/techs/detail.html
{% extends 'mybase.html' %}
{% load wagtailimages_tags %}
{% load wagtailcore_tags %}
{% load book_extras %}

{% block content %}
    <div class="row">
        <div class="col s12 m10 push-m1 l8 push-l2">

            <div class="item-details">
                <div class="row">
                    <p class="item-title center-on-small-only">{{ tech.title }}</p>
                </div>

                <div class="row">
                    {{ tech.body|richtext }}
                </div>

                {% if tech.related_article_links.all %}
                    <div class="row">
                        <p class="related-section-title">Статьи</p>
                        <ul class="collapsible" data-collapsible="accordion">
                            {% for link in tech.related_article_links.all %}
                                <li>
                                    <div class="collapsible-header">
                                        <i class="material-icons">keyboard_arrow_down</i>
                                        {{ link.name }}
                                    </div>
                                    <div class="collapsible-body">
                                        <div class="action-buttons">
                                            <a href="{{ link.url }}"
                                               class="waves-effect waves-light btn">
                                                Читать
                                            </a>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                {% if tech.related_video_links.all %}
                    <div class="row">
                        <p class="related-section-title">Видео</p>
                        <ul class="collapsible" data-collapsible="accordion">
                            {% for link in tech.related_video_links.all %}
                                <li>
                                    <div class="collapsible-header">
                                        <i class="material-icons">keyboard_arrow_down</i>
                                        {{ link.name }}
                                    </div>
                                    <div class="collapsible-body">
                                        <p>
                                            {{ link.description|richtext }}
                                        </p>
                                        {% include_block link.video %}
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                {% if tech.books.all %}
                    <div class="row">
                        <p class="related-section-title">Книги</p>
                        <ul class="collapsible" data-collapsible="accordion">
                            {% for tech_book_relationship in tech.books.all %}
                                {% with book=tech_book_relationship.book %}
                                    <li>
                                        <div class="collapsible-header">
                                            <i class="material-icons">keyboard_arrow_down</i>
                                            {{ book.title }}
                                        </div>
                                        <div class="collapsible-body">
                                            <p>{{ book.description|richtext }}</p>
                                            {% extended_book_tags book %}
                                            <div class="action-buttons">
                                                <a href="{% url 'books:detail' book.id %}"
                                                   class="waves-effect waves-light btn">
                                                    Описание
                                                </a>
                                                <a href="{{ book.file.url }}"
                                                   class="waves-effect waves-pdf-red btn">
                                                    Скачать
                                                </a>
                                            </div>
                                        </div>
                                    </li>
                                {% endwith %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock content %}

sturm/templates/techs/index.html
{% extends 'mybase.html' %}
{% block content %}
    <div class="row">
        <div class="col s12 l8 push-l2">
            <div class="item-index">
                {% if tech_list %}
                    <ul>
                        {% for tech in tech_list %}
                            <li class="item-card">
                                <div class="card-content">
                                    <p class="item-title">{{ tech.title }}</p>
                                </div>
                                {% if tech.tags.names %}
                                    <div class="tag-container">
                                        {% for tag in tech.tags.names %}
                                            <div class="tag-chip">{{ tag }}</div>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                                <div class="card-action action-buttons">
                                    <a href="{% url 'techs:detail' tech.id %}" class="waves-effect waves-light btn">Описание</a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>Библиотек нет</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

sturm/templates/techs/main.html
{% extends 'mybase.html' %}
{% block content %}
    <div class="row">
        <div class="col s12 l8 push-l2">
            <div class="row section">
                <div class="col s12 l4">
                    <a href="{% url "techs:category-index" category="orm" %}">
                        <div class="card tink-blue-grey white-text">
                            <div class="card-content">
                                <span class="card-title">Базы данных и ORM</span>
                                <p class="light">Как хранить информацию</p>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col s12 l4">
                    <div class="card tink-blue-grey white-text">
                        <div class="card-content">
                            <span class="card-title">Фреймворки</span>
                            <p class="light">Основы основ</p>
                        </div>
                    </div>
                </div>
                <div class="col s12 l4">
                    <div class="card tink-blue-grey white-text">
                        <div class="card-content">
                            <span class="card-title">Веб</span>
                            <p class="light">Сделай контент доступным</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}