books/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from books import views
from books.views import SpecificIndexView

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^select/$', views.SelectorView.as_view(), name='select'),
    url(r'^(?P<languages>[\w\-\*]+)/(?P<techs>[\w\-\*]+)/(?P<tags>[\w\-\*]+)/$', SpecificIndexView.as_view(), name='specific_index'),
    url(r'^rest/status/update/$', views.StatusUpdateView.as_view(), name='status_update')
]

sturm/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls.static import static
from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [

    url(r'^admin/', include(wagtailadmin_urls)),

    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^books/', decorator_include(login_required, 'books.urls', namespace="books")),
    url(r'^techs/', decorator_include(login_required, 'techs.urls', namespace="techs")),
    url(r'^projects/', decorator_include(login_required, 'projects.urls', namespace="projects")),
    url(r'^lessons/', decorator_include(login_required, 'lessons.urls', namespace="lessons")),
    url(r'^students/', decorator_include(login_required, 'students.urls', namespace="students")),

    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', login_required(search_views.search), name='search'),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:

    url(r'^', login_required(TemplateView.as_view(template_name='index.html')), name="home"),

    url(r'', decorator_include(login_required, wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.db.models import CharField
from django.db.models import ManyToManyField
from modelcluster.fields import ParentalKey
from taggit.managers import TaggableManager
from wagtail.wagtailadmin.edit_handlers import FieldPanel, PageChooserPanel, InlinePanel
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailcore.models import Page
from wagtail.wagtaildocs.edit_handlers import DocumentChooserPanel
from wagtail.wagtailsearch import index
from django.utils.encoding import python_2_unicode_compatible
from wagtail.wagtailsnippets.edit_handlers import SnippetChooserPanel

from wagtail.wagtailsnippets.models import register_snippet

from books.ru_taggit import RuTaggedItem


class Book(Page):
    parent_page_types = ['books.BookIndex']

    author = CharField(max_length=200, blank=False, null=False)
    description = RichTextField(blank=True)
    language = models.ForeignKey(
        'books.Language',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    lessons = ManyToManyField('lessons.Lesson', through='lessons.LessonBookRelationship')

    tags = TaggableManager(through=RuTaggedItem, blank=True)

    file = models.ForeignKey(
        'wagtaildocs.Document',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    search_fields = Page.search_fields + [
        index.SearchField('description'),
    ]

    content_panels = Page.content_panels + [
        FieldPanel('author'),
        FieldPanel('description', classname="full"),
        SnippetChooserPanel('language'),
        DocumentChooserPanel('file'),
        InlinePanel('techs', label="Mentioned technologies"),
        InlinePanel('students', label="Students"),
        FieldPanel('tags'),
    ]

    def __str__(self):
        return self.name


@register_snippet
@python_2_unicode_compatible
class Language(models.Model):
    name = models.CharField(max_length=20, null=False, blank=False)
    slug = models.CharField(max_length=20, null=False, blank=False)

    panels = [
        FieldPanel('name'),
        FieldPanel('slug'),
    ]

    def __str__(self):
        return self.name


class BookStudentRelationship(models.Model):
    book = ParentalKey(Book, related_name='students')
    student = models.ForeignKey('students.Student')

    recommend = models.CharField(max_length=20, default="no")
    status = models.CharField(max_length=20, default="no")

    panels = [
        SnippetChooserPanel('student'),
        FieldPanel('recommend'),
        FieldPanel('status'),
    ]


class BookTechRelationship(models.Model):
    book = ParentalKey(Book, related_name='techs')
    tech = models.ForeignKey('techs.Tech')

    panels = [
        PageChooserPanel('tech', 'techs.Tech'),
    ]


class BookIndex(Page):
    subpage_types = ['books.Book']

books/forms.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django import forms
from taggit.models import Tag

# class StatusForm(forms.Form):
#     STATUS_CHOICES = [('no', 'Еще не читал'),
#                       ('inprog', 'Сейчас читаю'),
#                       ('yes', 'Уже прочитал')]
#     status = forms.MultipleChoiceField(
#         choices=STATUS_CHOICES,
#         widget=Select,
#     )
from techs.models import Tech


class BookSelectForm(forms.Form):
    LANG_CHOICES = [('en', 'Английский'),
                    ('ru', 'Русский')]
    LANG_CHOICES += [('any', 'Любые')]
    languages = forms.MultipleChoiceField(
        label="Языки",
        choices=LANG_CHOICES,
    )

    TECH_CHOICES = [(tech.title, tech.title) for tech in Tech.objects.all()]
    TECH_CHOICES += [('any', 'Любые')]
    techs = forms.MultipleChoiceField(
        label="Технологии",
        choices=TECH_CHOICES,
    )

    TAG_CHOICES = [(tag.slug, tag.name.title()) for tag in Tag.objects.all()]
    TAG_CHOICES += [('any', 'Любые')]
    tags = forms.MultipleChoiceField(
        label="Тэги",
        choices=TAG_CHOICES,
    )

books/views.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-
from operator import and_

from django.db.models import Q
from django.urls import reverse
from django.views import generic
from rest_framework.response import Response
from rest_framework.views import APIView

from books.forms import BookSelectForm
from books.models import Book, BookStudentRelationship
from techs.models import Tech

always_true_criteria = ~Q(pk=None)

class IndexView(generic.ListView):
    template_name = 'books/index.html'
    context_object_name = 'latest_book_list'

    def get_criteria_list(self):
        return [always_true_criteria]

    def get_status(self, book_list):
        connection_list = self.request.user.bookstudentrelationship_set.all()

        for book in book_list:
            for connection in connection_list:
                if book.id == connection.book.id:
                    book.status = connection.status
                    book.recommend = connection.recommend
            if not hasattr(book, 'status'):
                book.status = 'no'
            if not hasattr(book, 'recommend'):
                print("here")
                book.recommend = 'no'
            book.recommend = "recommend-" + str(book.recommend)
            print(book.recommend)

    def get_queryset(self):
        book_list = Book.objects \
            .filter(reduce(and_, self.get_criteria_list())) \
            .distinct()

        # tech_list = Tech.objects.all()
        # for tech in tech_list:
        #     print(tech)
        # TECH_CHOICES = [(tech.title.lower(), tech.title) for tech in Tech.objects.all()]
        # print(TECH_CHOICES)

        self.get_status(book_list)

        return book_list


class SpecificIndexView(IndexView):
    def get_criteria_list(self):
        languages = self.kwargs['languages'].split('*')
        if languages != ["any"]:
            lang_criteria = Q(language__slug__in=languages)
        else:
            lang_criteria = always_true_criteria

        techs = self.kwargs['techs'].split('*')
        if "any" not in techs:
            print("Getting tech criteria")
            tech_criteria = Q(techs__tech__title__in=techs)
        else:
            tech_criteria = always_true_criteria

        tags = self.kwargs['tags'].split('*')
        if "any" not in tags:
            tag_criteria = Q(tags__slug__in=tags)
        else:
            tag_criteria = always_true_criteria

        return [lang_criteria, tech_criteria, tag_criteria]


class DetailView(generic.DetailView):
    model = Book
    template_name = 'books/detail.html'


class SelectorView(generic.FormView):
    template_name = 'books/selector.html'
    form_class = BookSelectForm

    def form_valid(self, form):
        delim = '*'
        self.kwargs['languages'] = delim.join(form.cleaned_data['languages'])
        self.kwargs['techs'] = delim.join(form.cleaned_data['techs'])
        self.kwargs['tags'] = delim.join(form.cleaned_data['tags'])
        return super(SelectorView, self).form_valid(form)

    def get_success_url(self):
        languages = self.kwargs['languages']
        techs = self.kwargs['techs']
        tags = self.kwargs['tags']
        return reverse(
            'books:specific_index',
            kwargs={
               'languages': languages,
               'techs': techs,
               'tags': tags
           }
        )


class StatusUpdateView(APIView):
    def post(self, request, format=None):
        book_id = request.data['book_id']
        new_status = request.data['new_status']

        print(new_status)

        student_id = self.request.user.id
        print("Student id: " + str(student_id))
        BookStudentRelationship.objects.update_or_create(student__pk=student_id,
                                                         book__pk=book_id,
                                                         defaults={
                                                             'student_id': student_id,
                                                             'book_id': book_id,
                                                             'status': new_status}
                                                         )

        return Response("Status updated successfully")

sturm/templates/books/detail.html
{% extends 'mybase.html' %}
{% load wagtailimages_tags %}
{% load wagtailcore_tags %}
{% load book_extras %}

{% block content %}
    <div class="row">
        <div class="col s12 m10 push-m1 l8 push-l2">
            <div class="item-details">
                <p class="item-title">{{ book.title }}</p>
                <p class="item-author left-align">{{ book.author }}</p>
                <div class="item-description-container">
                    <div class="item-description">{{ book.description|richtext }}</div>
                </div>
                {% extended_book_tags book %}
                {#                {% if book.techs.all %}#}
                {#                    <div class="collection">#}
                {#                        {% for book_tech_relationship in book.techs.all %}#}
                {#                            {% with  book_tech_relationship.tech as tech %}#}
                {#                                <a href="{% url 'techs:detail' tech.id %}" class="collection-item">{{ tech.title }}</a>#}
                {#                            {% endwith %}#}
                {#                        {% endfor %}#}
                {#                    </div>#}
                {#                {% endif %}#}
                <a class="waves-effect waves-light pdf-btn btn" href="{{ book.file.url }}">
                    <i class="material-icons left">library_books</i>
                    PDF
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

sturm/templates/books/extended_book_tags.html
{% if book.tags.names or book.language or book.techs.all %}
    <div class="tag-container">
        {% for book_tech_relationship in book.techs.all %}
            {% with book_tech_relationship.tech as tech %}
                <a class="tag-chip waves-effect"
                   href="{% url 'techs:detail' tech.id %}">
                    {{ tech.title|lower }}
                </a>
            {% endwith %}
        {% empty %}
        {% endfor %}
        {% for tag in book.tags.all %}
            <a class="tag-chip waves-effect"
               href="{% url 'books:specific_index' languages='any' techs='any' tags=tag.slug %}">
                {{ tag.name }}
            </a>
        {% empty %}
        {% endfor %}
        {% if book.language %}
            {% with book.language as language %}
                <a class="tag-chip waves-effect"
                   href="{% url 'books:specific_index' languages=language.slug techs='any' tags='any' %}">
                    {{ language }}
                </a>
            {% endwith %}
        {% endif %}
    </div>
{% endif %}

sturm/templates/books/index.html
{% extends 'mybase.html' %}
{% load book_extras %}

{% block content %}
    <div class="row">
        <div class="col s12 l8 push-l2">
            <div class="row">
                <div class="center-align">
                    <a class="waves-effect waves-light btn start-search-btn tink-gold black-text"
                       href="{% url 'books:select' %}">Поиск</a>
                </div>
            </div>
            <div class="row">
                <div class="item-index">
                    {% if latest_book_list %}
                        <ul>
                            {% for book in latest_book_list %}
                                <li class="item-card {{ book.recommend }}">
                                    <div class="card-content">
                                        <p class="item-title">{{ book.title }}</p>
                                        <p class="item-author">{{ book.author }}</p>
                                    </div>
                                    {% extended_book_tags book %}
                                    <div class="card-action">
                                        <span class="action-buttons">
                                            <a href="{% url 'books:detail' book.id %}"
                                               class="waves-effect waves-light btn">
                                                Описание
                                            </a>
                                            <a href="{{ book.file.url }}"
                                               class="waves-effect waves-pdf-red btn">
                                                Скачать
                                            </a>
                                        </span>
                                        <span class="switch book-status-switch">
                                            <span class="book-id-source" hidden="hidden">{{ book.id }}</span>
                                            <span class="book-status-source" hidden="hidden">{{ book.status }}</span>
                                            <label>
                                                Не читал
                                                <input type="checkbox">
                                                <span class="lever"></span>
                                                Читал
                                            </label>
                                        </span>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>Книг нет</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

sturm/templates/books/selector.html
{% extends 'mybase.html' %}

{#{% load mezzanine_tags %}#}

{% block content %}
    <form class="book-selector-form" action="/books/select/" method="post" id="selector-form">
        {% csrf_token %}
        <div class="row">
            {% for field in form %}
                <div class="col s12 m4">
                    <div class="card grey lighten-4">
                        <div class="card-content">
                            <span class="card-title black-text">{{ field.label }}</span>
                            {% for choice in field.field.choices %}
                                <p>
                                    {% if field.name == "languages" %}
                                        <input name="{{ field.name }}" type="checkbox" value="{{ choice.0 }}"
                                               id="{{ field.name }}+{{ choice.0 }}" checked="checked"/>
                                    {% else %}
                                        <input name="{{ field.name }}" type="checkbox" value="{{ choice.0 }}"
                                               id="{{ field.name }}+{{ choice.0 }}"/>
                                    {% endif %}
                                    <label for="{{ field.name }}+{{ choice.0 }}"
                                           class="black-text">{{ choice.1 }}</label>
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col s12">
                <div class="center-align">
                    <button class="btn waves-effect waves-light tink-gold black-text" type="submit" value="Submit">Найти
                    </button>
                </div>
            </div>
        </div>
        {% for field in form %}
            {% if field.errors %}
                <div class="row">
                    <div class="card red white-text">
                        <div class="card-content">
                            <ol>
                                {% for error in field.errors %}
                                    <li><strong>{{ error|escape }}</strong></li>
                                {% endfor %}
                            </ol>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </form>
{% endblock content %}