books/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from books import views
from books.views import SpecificIndexView

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^select/$', views.SelectorView.as_view(), name='select'),
    url(r'^(?P<languages>[\w\-\*]+)/(?P<techs>[\w\-\*]+)/(?P<tags>[\w\-\*]+)/$', SpecificIndexView.as_view(), name='specific_index'),
    url(r'^rest/status/update/$', views.StatusUpdateView.as_view(), name='status_update')
]

sturm/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls.static import static
from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [

    url(r'^admin/', include(wagtailadmin_urls)),

    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^books/', decorator_include(login_required, 'books.urls', namespace="books")),
    url(r'^techs/', decorator_include(login_required, 'techs.urls', namespace="techs")),
    url(r'^projects/', decorator_include(login_required, 'projects.urls', namespace="projects")),
    url(r'^lessons/', decorator_include(login_required, 'lessons.urls', namespace="lessons")),
    url(r'^students/', decorator_include(login_required, 'students.urls', namespace="students")),

    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', login_required(search_views.search), name='search'),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:

    url(r'^', login_required(TemplateView.as_view(template_name='index.html')), name="home"),

    url(r'', decorator_include(login_required, wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techs/urls.py
from django.conf.urls import url

from techs import views
from techs.views import CategoryIndexView

urlpatterns = [
    url(r'^main/$', views.MainView.as_view(), name='main'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<category>[\w]+)/$', CategoryIndexView.as_view(), name='category-index'),
]

sturm/templates/base.html
{% load static wagtailuserbar %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>
            {% block title %}
                {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
                {% with self.get_site.site_name as site_name %}
                    {% if site_name %}- {{ site_name }}{% endif %}
                {% endwith %}
            {% endblock %}
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/aurelian.css' %}">

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% wagtailuserbar %}

        {% block content %}{% endblock %}

        {# Global javascript #}
        <script type="text/javascript" src="{% static 'js/aurelian.js' %}"></script>

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

sturm/templates/index.html
{% extends "mybase.html" %}

{% block content %}
    <div class="row homepage-card-container">
        <div class="col s12 m8 push-m2 l4">
            <a href="{% url "books:index" %}">
                <div class="homepage-card">
                    <div class="card-content center-align">
                        <span>Книги</span>
                    </div>
                </div>
            </a>
        </div>
        <div class="col s12 m8 push-m2 l4">
            <a href="{% url "techs:index" %}">
                <div class="homepage-card">
                    <div class="card-content center-align">
                        <span>Технологии</span>
                    </div>
                </div>
            </a>
        </div>
        <div class="col s12 m8 push-m2 l4">
            <a href="{% url "techs:main" %}">
                <div class="homepage-card">
                    <div class="card-content center-align">
                        <span>Техно-Кат</span>
                    </div>
                </div>
            </a>
        </div>
        <div class="col s12 m8 push-m2 l4">
            <a href="{% url "lessons:index" %}">
                <div class="homepage-card">
                    <div class="card-content center-align">
                        <span>Уроки</span>
                    </div>
                </div>
            </a>
        </div>
        <div class="col s12 m8 push-m2 l4">
            <a href="{% url "projects:index" %}">
                <div class="homepage-card">
                    <div class="card-content center-align">
                        <span>Проекты</span>
                    </div>
                </div>
            </a>
        </div>
        <div class="col s12 m8 push-m2 l4">
            <a href="{% url "students:index" %}">
                <div class="homepage-card">
                    <div class="card-content center-align">
                        <span>Люди</span>
                    </div>
                </div>
            </a>
        </div>
        {#        <div class="col s12 m8 push-m2 l4">#}
        {#            <a href="#">#}
        {#                <div class="homepage-card">#}
        {#                    <div class="card-content center-align">#}
        {#                        <span>Кабинет</span>#}
        {#                    </div>#}
        {#                </div>#}
        {#            </a>#}
        {#        </div>#}
    </div>
{% endblock content %}

{#{% extends "base.html" %}#}
{#{% load i18n %}#}
{##}
{#{% block meta_title %}{% trans "Home" %}{% endblock %}#}
{#{% block title %}{% trans "Home" %}{% endblock %}#}
{##}
{#{% block breadcrumb_menu %}#}
{#<li class="active">{% trans "Home" %}</li>#}
{#{% endblock %}#}
{##}
{#{% block main %}#}
{#{% blocktrans %}#}
{#<h2>Congratulations!</h2>#}
{#<p>#}
{#    Welcome to your new Mezzanine powered website.#}
{#    Here are some quick links to get you started:#}
{#</p>#}
{#<ul>#}
{#    <li><a href="/admin/">Log in to the admin interface</a></li>#}
{#    <li><a href="http://mezzanine.jupo.org/docs/content-architecture.html">Creating custom page types</a></li>#}
{#    <li><a href="http://mezzanine.jupo.org/docs/frequently-asked-questions.html#templates">Modifying HTML templates</a></li>#}
{#    <li><a href="http://mezzanine.jupo.org/docs/frequently-asked-questions.html#why-isn-t-the-homepage-a-page-object-i-can-edit-via-the-admin">Changing this homepage</a></li>#}
{#    <li><a href="http://mezzanine.jupo.org/docs/frequently-asked-questions.html">Other frequently asked questions</a></li>#}
{#    <li><a href="http://mezzanine.jupo.org/docs/configuration.html#default-settings">Full list of settings</a></li>#}
{#    <li><a href="http://mezzanine.jupo.org/docs/deployment.html">Deploying to a production server</a></li>#}
{#</ul>#}
{#{% endblocktrans %}#}
{#{% endblock %}#}

sturm/templates/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

sturm/templates/mybase.html
{# base template #}
{% load staticfiles %}

{% load wagtailimages_tags %}
{% load wagtailcore_tags %}

<html>
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Tangerine">

    <link rel="stylesheet" type="text/css" href="{% static 'css/screen.css' %}"/>

    <script src="{% static "js/jquery.js" %}"></script>
    <script src="{% static "js/bin/materialize.js" %}"></script>
    <script src="{% static "js/rango-jquery.js" %}"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
</head>
<body>
<header>
    <nav>
        <div class="nav-wrapper">
            <a href="{% url "home" %}" class="brand-logo">#nc-edu</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url "books:index" %}">Книги</a></li>
                <li><a href="{% url "techs:index" %}">Технологии</a></li>
                <li><a href="{% url "lessons:index" %}">Уроки</a></li>
                <li>
                    {% if request.user.is_authenticated %}
                        <a href='{% url "logout" %}?next={{ request.path }}'>Выйти</a>
                    {% else %}
                        <a href='{% url "login" %}?next={{ request.path }}'>Войти</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
</header>
<main>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</main>
<footer class="page-footer">
    {#    <div class="container">#}
    {#        <div class="row">#}
    {#            <div class="col l6 s12">#}
    {#                <h5 class="white-text">Footer Content</h5>#}
    {#                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer#}
    {#                    content.</p>#}
    {#            </div>#}
    {#            <div class="col l4 offset-l2 s12">#}
    {#                <h5 class="white-text">Links</h5>#}
    {#                <ul>#}
    {#                    <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>#}
    {#                    <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>#}
    {#                    <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>#}
    {#                    <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>#}
    {#                </ul>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}
    <div class="footer-copyright">
        <div class="container">
            © 2017 Netcracker Technology
            {#            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>#}
        </div>
    </div>
</footer>
</body>
</html>